language: cpp
compiler:
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y llvm-3.4 llvm-3.4-dev libgmpxx4ldbl libeigen3-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm && brew link --force llvm; fi
notifications:
  email:
    recipients:
      - libint@valeyev.net
    on_success: change
    on_failure: always
os:
  - linux
after_failure: cat ./config.log
script: ./autogen.sh && ./configure CXXFLAGS='-std=c++11' && make && make check
