os:
  - linux
language: cpp
compiler:
  - clang
  - gcc
env:
  - GCC_VERSION=4.8
  - GCC_VERSION=4.9
matrix:
  exclude:
    - compiler: clang
      env: GCC_VERSION=4.9
before_install:
  - ./bin/travisci_before_$TRAVIS_OS_NAME.sh
script:
  - ./autogen.sh && ./configure CXXFLAGS='-std=c++11' CPPFLAGS='-I/usr/include/eigen3' --with-max-am=2,2 --with-eri-max-am=2,1 --with-eri3-max-am=3,2 --enable-eri=1 --enable-eri3=1 && make -j2 && make check
after_failure: cat ./config.log && cat include/libint2/config.h
notifications:
  email:
    recipients:
      - libint+travisci@valeyev.net
    on_success: change
    on_failure: always
