os:
  - linux
language: cpp
compiler:
  - clang
  - gcc
env:
  - GCC_VERSION=4.8
  - GCC_VERSION=4.9
  - GCC_VERSION=5
matrix:
  exclude:
    - compiler: clang
      env: GCC_VERSION=4.8
    - compiler: clang
      env: GCC_VERSION=4.9
before_install:
  - ./bin/travisci_before_$TRAVIS_OS_NAME.sh
script:
  - ./bin/travisci_build_$TRAVIS_OS_NAME.sh
after_failure:
  - cat include/libint2/config.h
  - cat config.log
  - cat export_build/config.log
  - ls -l export_build
notifications:
  email:
    recipients:
      - libint+travisci@valeyev.net
    on_success: change
    on_failure: always
